### ISSUE TITLE
Video embed url only add an extra closing </div>

### ISSUE THREAD

**Issue by afincato** [distantnative/embed#72] opened 2017-02-02 15:42 UTC
I'm reporting this here for future reference in case someone else will stumble upon this problem. 

It happens to me only in one kirby installation. When I tried to reproduce it in another one (still with `kirby at 2.4.1`) the problem did not happen. So I am not sure what are the reasons causing this.

So, whenever I am embedding a video (youtube, vimeo) through a `kirbytag`, the `div` wrapper print an extra closing `</div>` at the end of the `oembed div`, closing prematurely the `div` container that is wrapping, for example, the main text column. This messes up with the overall page structure.

Looking around in the plugin files, I figured that by commenting out the closing `</div>` of the file

```
site/plugins/oembed/core/snippets/thumb.php
```

the problem does not happen anymore, while all `oembed divs` are still properly closed.

It is not a real a solution, but for now at least it's working. Not sure if it is connected with issue #67 [see in particular](https://github.com/distantnative/oembed/issues/67#issuecomment-273697228).

Will report back if I find something.

**Comment by distantnative** [comment] 2017-03-10 16:10
I'm currently traveling in Mexico doing research for my PhD. I will be back on a laptop by the end of the month and then I'll look at this in detail.

**Comment by distantnative** [comment] 2017-03-22 12:20
I had a look at this but cannot reproduce it. And I am surprised: Since the main wrapper of the oembed code added is a `figure` tag, even if there were too many closing div's from the thumb code inside it, this should not cause other divs from the main page structure to be closed. As they are contained by the figure container:

```
<figure class="oembed oembed--video oembed--YouTube " style="padding-top:56.25%">
  <iframe width="480" height="270" data-src="…" frameborder="0" allowfullscreen></iframe>
  <div class="oembed__thumb" style="background-image:url(…');" title="…"><img src="…" … /></div>
</figure> 
```

**Closed** 2017-03-31 13:16 UTC
